### ISSUE TITLE
Auto-wrapping methods and prevent naming collisions

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-bridge#182]
The current auto-bindables code wraps the `options` object that's passed into the Kendo controls

We've got nothing at the moment that automatically wraps methods on the Kendo widget itself which means you either have to explicitly wrap the methods manually or talk to the widget property on the wrapper:

```
this.myDropDownList.widget.value("fred")
```

Generating wrappers for the methods should be possible but it raises a small but important issue - naming collisions

Since the bindable generator looks at the options object, it creates bindable properties that don't exist in the widgets API.

Take `DropDownList` for example; the control has a `value()` method to get/set the current value. The options object has a `value` property which sets up the initial value.

This presents a collision, as you cannot have a bindable property and a method with the same name on the same wrapper object. This also presents the same issue with event names.

A possible solution is to add a prefix to bindable properties and events. This could be:

* methods 
  * DOM: no change
  * JS: no change
* bindables 
  * DOM: `k-bindable-name`
  * JS: `kBindableName`
* events
  * DOM: `k-on-event-name`
  * JS: `kOnEventName`

It means a couple of small conventions to learn for the user, but it means we can probably auto-implement most of the Kendo functionality. 95% of the time we just want to wrap the existing implementation but not have that extra layer of indirection via `wrapper.widget.xyz()`

It means the API looks the same to an experienced Kendo user - I'd rather keep that as a selling point

**Comment by charlespockert** [comment]
@adriatic @JeroenVinke - oops forgot to ping you both :)

This also lends itself to: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/179

Not the issue itself but the implementation of the control using a `value` property which is not what the widget uses (widget uses a `value()` method)

**Comment by JeroenVinke** [comment]
I'm going to throw another one out here..

We can rename `<au-kendo-sparkline>` to `<k-sparkline>` :) shorter is better, no?

**Comment by JeroenVinke** [comment]
about collisions.

When they happen, someone can just do this I think:

```
<require from="./k-button" as "karma-button"></require>
<karma-button></karma-button>

<div karma-button></div>
```

**Comment by JeroenVinke** [comment]
@charlespockert @adriatic I have just refactored the bindable names and event prefix. 

An example: `<button k-button="k-enable.bind: enabled" k-on-click.trigger="test()">Click me</button>`

This allows us to create an `enable()` function on our wrapper, which previously wasn't possible because it would've collisioned with the `enable` bindable property. Now that this property is called `kEnable` (and for consistancy, we prefix all of the properties), we can safely add an `enable()` function.

@charlespockert I don't think we should generate the methods as I expect we will run into a lot of trouble. Do you still want to do this?

**Comment by JeroenVinke** [comment]
I also may have messed some samples up, refactoring was a lot of work so I quickly went through them all.

**Comment by JeroenVinke** [comment]
Instead of getting these of the controls automatically, we can provide an array of method names in the wrapper. The widgetbase can then create wrapper methods for methods like:

```
  setDataSource(value) {
    if (this.widget) {
      return this.widget.setDataSource(value);
    }
  }
```

it's not as automatic as finding the methods on the Kendo control itself, but it should save us a lot of boilerplate code

**Comment by JeroenVinke** [comment]
We don't need this anymore, as people primarily will use the original Kendo control, not our wrapper
