### ISSUE TITLE
Create the release version of the plugin

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#223]
Once we have that created, we can ensure that all documents referencing it use the correct URLs

**Example**: `package.json` reference to our plugin
```
"aurelia-kendoui-plugin": "github:aurelia-ui-toolkits/aurelia-kendoui-plugin@master"
```
would lose the `@master` part.

I believe that we can make the reference to always point to the current release.

**Comment by adriatic** [comment]
Just as I finished typing this, I got the email from github about https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/98

**Comment by JeroenVinke** [comment]
@adriatic I figured that our first release would be 0.1.0

Then when we create a new set of wrappers, that would be 0.2.0. And after we have finished all wrappers, then we can release 1.0.0

**Comment by adriatic** [comment]
Agree wholeheartedly

**Comment by JeroenVinke** [comment]
should we follow Aurelia's footsteps and publish to npm too? we can also update the [jspm registry](https://github.com/jspm/registry/blob/master/registry.json#L123) so people will download from npm instead of github. That will help prevent people having to enter their Github credentials as they could be rate limited by Github, npm has no such restraints

**Comment by adriatic** [comment]
### YES

**Comment by adriatic** [comment]
Without any desire to be perceived as cocky, we should use all Aurelia's examples of smart things to do - not only because this **is smart to do**, but also simplifies any possible "integrations" with Aurelia
