### ISSUE TITLE
Composition instead of inheritance

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#267]
Necessary for https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/262

**Comment by adriatic** [comment]
Using some "loose language" one could say that composition and inheritance serve the same purpose and in the case of JavaScript (which is different from C#) even the implementation is "similar" in the sense that in the case of composition you provide "links to parents" manually and in the case of inheritance you rely on someone else (JavaScript interpreter) to do that.

As I am just vaguely aware of the JavaScript inheritance concepts, can someone explain what entity in Aurelia handles the case it gave us problems - (binding, I would guess).

Also, why did you (Jeroen) elected to use inheritance in the first place?

**Comment by charlespockert** [comment]
Since classical inheritance doesn't *really* exist in JS - I'd warrant that the issue comes from the way the object is represented by the output of the transpiler and how decorators work.

It's worth looking at - there must be a good reason why Aurelia doesn't support this yet, probably due to a technical hitch. Worth looking into though - maybe we can come up with a solution for Au team.

**Comment by adriatic** [comment]
Thanks for the response, Charles - I was hoping that you would react like that (sometimes the core team is really spread too thin, so expecting that we might be of some help is not too much of an exaggeration :-)

**Comment by JeroenVinke** [comment]
This is now in master
