### ISSUE TITLE
rename demo-kendo to aurelia-kendoui-catalog

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#328]
see https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/88

**Comment by JeroenVinke** [comment]
done

**Comment by JeroenVinke** [comment]
and reverted as this changed the URL from `http://aurelia-ui-toolkits.github.io/demo-kendo` to `http://aurelia-ui-toolkits.github.io/aurelia-kendoui-catalog`, which would break many bookmarks. Lets wait for JSPM 0.17 so we can get rid of demo-kendo, instead of facing the consequence of having the url change multiple times

**Comment by adriatic** [comment]
That is fine.
