### ISSUE TITLE
k-button naming collision

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#383]
```
  <k-notification id="centeredNotification"
                  k-stacking="down",
                  k-on-show.delegate="onShow($event.detail)"
                  k-button.bind="true"
                  k-widget.bind="centered"></k-notification>
```

it wants to load the Kendo Button because we have to use `k-button` in this sample

**Comment by adriatic** [comment]
I tried to run this sample in Dojo with `button` set to true and false - there was no visible change as a consequence of that setting - so I wonder what is the function of this setting? What happens if you do not bind it?

![image](https://cloud.githubusercontent.com/assets/2712405/13383506/84b3b2ba-de58-11e5-84d2-95513fff9410.png)

**Comment by JeroenVinke** [comment]
Still, I am not confident about this and worry this will bite us hard in the future. I propose we make changes to prefixes after we wrapped all controls (before beta). I'd rather deal with this earlier than later

**Comment by JeroenVinke** [comment]
Tracking in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/412
