### ISSUE TITLE
Update aurelia dependencies 

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#391]
Corejs dependency was removed so we need to check if everything works with the latest aurelia versions

**Comment by adriatic** [comment]
We need to establish a standard procedure for Aurelia specific updates. Here are some of the issues that we need to address.

### Put the order in the existing configuration files

1. We have two package.json files and related config.js files (one for the bridge, the second one for the catalog app)

2. I do not believe that we have yet defined the needed minimum aurelia framework components for either the bridge or the catalog side. at the moment we have 

**bridge**
```
    "dependencies": {
      "aurelia-binding": "npm:aurelia-binding@^1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@^1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@^1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@^1.0.0-beta.1.1.4",
      "aurelia-task-queue": "npm:aurelia-task-queue@^1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@^1.0.0-beta.1.1.1",
      "jquery": "components/jquery@2.1.4"
    },
   "devDependencies": {
      "aurelia-pal": "npm:aurelia-pal@^1.0.0-beta.1.1.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@^1.0.0-beta.1.1.2",
      "babel": "npm:babel-core@^5.8.22",
      "babel-runtime": "npm:babel-runtime@^5.8.20",
      "core-js": "npm:core-js@^2.1.0",
      "jquery": "components/jquery@2.1.4",
      "jquery.min": "components/jquery@2.1.4",
      "polymer/mutationobservers": "^0.4.2",
      "text": "systemjs/plugin-text@^0.0.4",
      "traceur": "jmcriffey/bower-traceur@0.0.91",
      "traceur-runtime": "jmcriffey/bower-traceur-runtime@0.0.91"
    }
```

**catalog**
```
  "jspm": {
    "dependencies": {
      "aurelia-binding": "npm:aurelia-binding@^1.0.0-beta.1.0.3",
      "aurelia-bootstrapper": "npm:aurelia-bootstrapper@^1.0.0-beta.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@^1.0.0-beta.1",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@^1.0.0-beta.1",
      "aurelia-framework": "npm:aurelia-framework@^1.0.0-beta.1.0.6",
      "aurelia-http-client": "npm:aurelia-http-client@^1.0.0-beta.1",
      "aurelia-loader": "npm:aurelia-loader@^1.0.0-beta.1",
      "aurelia-logging": "npm:aurelia-logging@^1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@^1.0.0-beta.1",
      "aurelia-pal": "npm:aurelia-pal@^1.0.0-beta.1.0.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@^1.0.0-beta.1.0.1",
      "aurelia-templating": "npm:aurelia-templating@^1.0.0-beta.1.0.2",
      "bootstrap": "github:twbs/bootstrap@^3.3.6",
      "css": "github:systemjs/plugin-css@0.1.20",
      "font-awesome": "npm:font-awesome@^4.5.0",
      "gka/chroma.js": "github:gka/chroma.js@^1.1.1",
      "google/code-prettify": "github:google/code-prettify@master",
      "jquery": "github:components/jquery@2.1.4",
      "jquery.min": "github:components/jquery@2.1.4",
      "json": "github:systemjs/plugin-json@^0.1.0",
      "prettify": "npm:prettify@^0.1.7",
      "prism": "github:PrismJS/prism@1.3.0",
      "showdown": "github:showdownjs/showdown@1.3.0",
      "showdown-prettify": "npm:showdown-prettify@^1.0.2",
      "text": "github:systemjs/plugin-text@^0.0.4"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  },
```

I am pretty sure that we list more aurelia framework components than we need, and it is quite possible that these might not be the same versions between the catalog and the bridge.

 ___To be verified___

### Define the update process

Before anything else, I want to ensure that the related package.json / config.js files are **always** in sync. The main problem in doing this is my suspicion that the relationship between them (managed by jspm) is too loosely coupled. So, I want to verify my "theory" how to tighten this relationship with Guy Bedford first and then apply it.

The problem is also how to apply the update that is limited to Aurelia only, without  the risk that running the `jspm update` does not create a tangled mess of updating all other parts that we did not want to get updated. So, we need to (in coordination with Rob) lock down all Aurelia independent modules and upgrade those only knowing that Aurelia needs newer versions specifically.

**Comment by Thanood** [comment]
Regarding the update alone, everything worked fine. I had to comment "runtime" from "babelOptions" to try to not use core-js at all. I wanted to try that and it works. :smile: 

I agree on the need to verify our minimum dependencies. I've created another issue on that on materialize bridge.

**Comment by JeroenVinke** [comment]
All the dependencies mentioned in the package.json of the plugin are used by the plugin and should therefore stay as they are. The weird thing is that we haven't locked down the version (we use the `^` in versions, which should tell JSPM to use that version or above) but it still creates forks.

```
    "dependencies": {
      "aurelia-binding": "npm:aurelia-binding@^1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@^1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@^1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@^1.0.0-beta.1.1.4",
      "aurelia-task-queue": "npm:aurelia-task-queue@^1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@^1.0.0-beta.1.1.1",
      "jquery": "components/jquery@2.1.4"
    },
```

**Comment by JeroenVinke** [comment]
> Regarding the update alone, everything worked fine. I had to comment "runtime" from "babelOptions" to try to not use core-js at all. I wanted to try that and it works

Great catch, works for kendoui-bridge too

**Comment by Thanood** [comment]
I don't get any forks on a fresh clone of kendoui-bridge.

**Comment by JeroenVinke** [comment]
yep, I just updated those versions

**Comment by Thanood** [comment]
That's an explanation. :smile:
