### ISSUE TITLE
BindingLanguage error

### ISSUE THREAD

**Issue by alexsurg** [aurelia-ui-toolkits/aurelia-kendoui-bridge#393]
Hi,

When i try to set up the bridge i get the following error:

Unhandled promise rejection Error: A BindingLanguage must implement parseText(...)
    at BindingLanguage.parseText (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.2/aurelia-templating.js:712:13)
    at ViewCompiler._compileNode (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.2/aurelia-templating.js:2103:79)
    at ViewCompiler._compileNode (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.2/aurelia-templating.js:2123:33)
    at ViewCompiler.compile (http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.2/aurelia-templating.js:2080:12)
    at http://localhost:32433/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.2/aurelia-templating.js:2720:49
    at g (http://localhost:32433/jspm_packages/npm/core-js@2.1.1/client/shim.min.js:2205:85)
    at http://localhost:32433/jspm_packages/npm/core-js@2.1.1/client/shim.min.js:2210:19
    at MutationObserver.e (http://localhost:32433/jspm_packages/npm/core-js@2.1.1/client/shim.min.js:2442:55)

I get the same error when i tried to use the KendoUI core or the vendors setup.

Do you have any idea how to fix it?

Thank,
Alex

**Comment by JeroenVinke** [comment]
Hey Alex. It seems that you are affected by some forks created by jspm. I will update our dependencies to the latest aurelia versions which should prevent this from happening. In the meantime, try and run jspm update.

**Comment by alexsurg** [comment]
Great, the jspm update solved it.

On an unrelated issue. I used the vendor approach and now when i use the bridge i see that it loads alot of Kendo js files, in my case i want to use only the Grid and the DropDown list and i dont want to load the rest of the kendo widgets like: treeview, datepicker, etc.

How can i set it to load only the js files that i need?
If i remove the unnecessary files i get a 404 eror and the project wont load

**Comment by alexsurg** [comment]
Also, i want to use a Kendo custom js file that contains all the necessary widget (i downloaded such a file from the Kendo site, it combines all the widgets that i use) to save the number of requests.

How can i modify this line in config.js to make it work:
"kendo.*": "vendors/js/kendo.*.js"

**Comment by JeroenVinke** [comment]
> Great, the jspm update solved it.

Glad that it's solved

> On an unrelated issue. I used the vendor approach and now when i use the bridge i see that it loads alot of Kendo js files, in my case i want to use only the Grid and the DropDown list and i dont want to load the rest of the kendo widgets like: treeview, datepicker, etc.

>How can i set it to load only the js files that i need?
If i remove the unnecessary files i get a 404 eror and the project wont load

In your main.js you probably have something like this:

`.plugin('aurelia-kendoui-bridge', kendo => kendo.pro())`

By calling the `.pro()` method you are saying that you want to use the entire Kendo suite. We actually have a builder pattern here where you can do this:`

`.plugin('aurelia-kendoui-bridge', kendo => kendo.kendoGrid().kendoDropDownList())`

Then only the grid and dropdownlist files should be loaded.


> Also, i want to use a Kendo custom js file that contains all the necessary widget (i downloaded such a file from the Kendo site, it combines all the widgets that i use) to save the number of requests.

> How can i modify this line in config.js to make it work:
"kendo.": "vendors/js/kendo..js"

Instead of using a custom .js file, I'd recommend to use aurelia's bundling library (aurelia-bundler) to bundle the Kendo files into a single file. You can find more information about this [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/bridge_developers_notes/5._on_bundling), and a repository that already does bundling can be found [here](https://github.com/aurelia-ui-toolkits/demo-kendo). Note the [bundles.json](https://github.com/aurelia-ui-toolkits/demo-kendo/blob/master/build/bundles.js). You should be able to bundle only the files that you need (the Grid and the Dropdownlist)

**Comment by alexsurg** [comment]
Thanks, i will use the aurelia bundler instead of the custom js file and replacing .pro() with the names of the widgets that i need did the trick.

One last question, i also need to use Kendo multi select in my project. Are you planning to support this widget any time soon?

**Comment by JeroenVinke** [comment]
> Are you planning to support this widget any time soon?

Yes, but I should mention that we discovered a bug that messes up the presentation when virtualization mode is used in combination with custom templates: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/368.

**Comment by alexsurg** [comment]
Thanks, please let me know when it released.

**Comment by JeroenVinke** [comment]
@alexsurg the multiselect has just been released in 0.5.0. About https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/368, this was indeed a bug in Kendo and it works fine with v2016.1.226

**Comment by alexsurg** [comment]
Great news, Thanks.
