### ISSUE TITLE
Catalog not running in Edge

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#407]
http://aurelia-ui-toolkits.github.io/demo-kendo/

 FORBIDDEN - The server understood the request, but is refusing to fulfil it.
(XHR): GET - https://sidecar.gitter.im/dist/sidecar.js.map

**Comment by JeroenVinke** [comment]
It is running but loads very slowly because we are not using the bluebird promise implementation

**Comment by adriatic** [comment]
Just tried the Edge (it still feels like IE and says IE):

![image](https://cloud.githubusercontent.com/assets/2712405/13609124/a9aa019a-e525-11e5-9264-91138eeb81c6.png)

and the app just shows "Loading" symbol forever - no messages on console, nothing showing on Network tab seems completely dead

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/demo-kendo/commit/c6caa2c3d2b16b97d9bb4d7167ca0817f6f71871

it worked after I removed sidecar from index.html

**Comment by adriatic** [comment]
So, it was just a reference to sidecar that caused the problem?

**Comment by JeroenVinke** [comment]
Yes

**Comment by Thanood** [comment]
@adriatic That is not an Edge screenshot. :smile: 

The catalog app takes around 30 seconds to load on Edge. This is with dev tools open. I've opened it because I wanted know if there is an error that's blocking the load and to have network time visible. There are no errors.

Have a look at the network panel in this screenshot.

![image](https://cloud.githubusercontent.com/assets/677826/13661149/5b3cafe6-e690-11e5-86ba-43b199cc2f24.png)

Edge version:

![image](https://cloud.githubusercontent.com/assets/677826/13661172/8aabff34-e690-11e5-99d4-1971c3c3c00a.png)
