### ISSUE TITLE
Ensure the consistency between the tutorials and code used in catalog app

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#420]
While this may not be urgent, I want to have it registered with the note that quality of the tutorials is inversely proportional to support requests. 

**[Here](https://github.com/aurelia-ui-toolkits/kendoui-templates-repository/issues/1#issuecomment-195390180)** is a detailed explanation.

**Comment by JeroenVinke** [comment]
I believe this issue was created because of https://github.com/aurelia-ui-toolkits/kendoui-templates-repository/issues/1#issuecomment-195390180. The code of the tutorial and of the real catalog does not have to be the same (the purpose of the real catalog is a bit different): https://github.com/aurelia-ui-toolkits/kendoui-templates-repository/issues/1#issuecomment-195409594
