### ISSUE TITLE
cascade & databound events for DropDownList with local data fire before k-widget binding

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#473]
Not really sure if it is a bug at all:
the cascade & databound events for DD list in the case of local data are invoked for the first time BEFORE k-widget binding (or <control>.ref). So the kendoUI widget reference is null at that point (the first occurence of cascade / databound events)
For remote data it works ok. If I use TaskQueue to handle those events, it works ok for local data too :).

**Comment by JeroenVinke** [comment]
Yep, this is a known limitation of the bridge. I wonder if we could raise a DOM event when the widget is ready... Like k-on-initialized.bind="doSomething()". Would that help you?

**Comment by smax48** [comment]
At the moment the current behavior doesn't really affect our code because all data is remote. The issue doesn't happen if a datasource receives data asynchronously (even in my tests when I use a Promise together with setTimeout(..., 0)). 
Am I right that the original KendoUI widget is ready (because something must send those cascade events :) ) but the k-widget binding for some reason cannot be resolved before and the widget wrapper is empty?
I haven't investigated the bridge code but it looks like that dispatching of k-on-cascade / k-on-databound events happens before the widget wrapper initialization but in the same sync call context... (because everything starts working once I introduce async behavior either in event handlers or in the datasource itself)

**Comment by JeroenVinke** [comment]
Yep, you got it right. With k-widget you are two way binding, and our wrappers sets the kWidget property after initializing the kendo control. However, this won't be propogated to your view-model until after the attached() callback of your vm.

The whole k-widget trickery is to expose the kendo control to your view-model. It works pretty well but sucks for usecases where you want to talk to the control in bind() or attached() because aurelias binding system isn't done yet. So if you have other ideas to expose the widget I am all ears :) 

We should be able to raise a DOM event that would allow you to have a function callback where we pass the kendo control instance to it as a parameter. Then you can use that before the k-widget binding is ready.

**Comment by JeroenVinke** [comment]
http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/7._what_you_need_to_know shows how to use the taskqueue to execute code after aurelia is done with setting up two way binding

**Comment by JeroenVinke** [comment]
I just noticed that the cascade and databound event passes along the Kendo widget as `sender`:  https://gist.run/?id=58bae9a9e177f1b4065c178e8766f0dc

**Comment by smax48** [comment]
I don't think that I need any additional functionality in regard to this
issue. I know that it works either with async datasource or with async
cascade/databound events handling (via TaskQueue).
Just wanted to clarify whether this is a bug or just a current aurelia
limitation.

Thanks for the example with the kendo widget as a parameter - I think this
solves all potential problems for me.
