### ISSUE TITLE
@delayed causing unit test to fail

### ISSUE THREAD

**Issue by rinobatin** [aurelia-ui-toolkits/aurelia-kendoui-bridge#512]
I have a class that looks like this:

```
//imports...
export class Widget {

 @delayed()
 attached(){
    this.kendoTree.expand('.k-item');
 }

}
```

And unit test (spec)

```
//imports...
describe('Widget', () => {
  let sut;
  let container;
beforeEach(() => {    
    container = new Container();
    Container.instance = container;
    sut = new Widget();
  });

 it('test1', () => {
     expect(1).toBe(1);
  });

})
```

If I run the test, I get ```Error: Cannot read property 'get' of undefined. Error loading <spec>```. If I remove ```@delayed()```, it works. I looked the code of ```delayed``` decorator and its using ```Container.instance.get()``` (DI container). I think ```beforeEach``` has setup the container properly.

A similar problem was logged [here](https://github.com/aurelia/dependency-injection/issues/57) and it was suggested not to use DI inside decorators.

I like ```@delayed``` because it's more convenient than
```
 this.tq.queueTask( () => {
     this.kendoTree.expand('.k-item'); 
 });
``` 
Any suggestions to restructure my code so I can continue using ```@delayed```?

**Comment by charlespockert** [comment]
@rinobatin You can probably get this unit test working if you use `https://github.com/aurelia/testing`, it allows you to bootstrap Aurelia with just the bits you need which you can include the `TaskQueue` which should enable the DI to work

I can only imagine this to be one of the following issues:

* You somehow have multiple type definitions of `Container` (less likely)

or 

* The decorators for the type are running before the container is configured (as you have stated). This could make sense as Aurelia imports modules dynamically on the fly, and since you are importing the modules into your tests you are likely running the decorators on import.

The above library works by running a mini Aurelia app lifecycle, so it imports your component dynamically, ensuring that the app is in the right state before you test your components.

**Comment by rinobatin** [comment]
@charlespockert, thanks for the reply. I also tried aurelia-testing but keep getting undefined StageComponent. I used jspm to install the npm package v0.3.0 but when I manually replaced the files with the github release, it worked!!! I logged an issue for someone to confirm.

Are you using the aurelia-testing npm package? My setup is typscript/systemjs/jasmine/karma.

**Comment by rinobatin** [comment]
Setting aside the issue with the aurelia-testing npm package, ```@delayed``` works fine with aurelia-testing but ```this.kendoTree``` is undefined which defeats the purpose of ```@delayed'```.

The view looks like this

```
<template> 
    Tree
    <div ak-treeview="k-data-source.bind: treeDS; 
        k-data-text-field.bind:'label';
        k-widget.bind:kendoTree; " >         
    </div> 
 </template>
```
