### ISSUE TITLE
Remove @delayed for attached() callback

### ISSUE THREAD

**Issue by bdenham** [aurelia-ui-toolkits/aurelia-kendoui-bridge#551]
We need a better way of accessing a view's kendoui control from the view-model. Currently we have to use <ak-kendo-control k-widget.bind="kendocontrol"> in the view, and access it from within the view-model's attached() callback (using the @delay workaround) in order to initialize / configure the kendocontrol during the loading lifecycle.

The current method works, but maybe we can find a way to either get rid of the @delay workaround and keep using the attached() callback, or tap into another event/method of the Aurelia component startup lifecycle.

**Comment by JeroenVinke** [comment]
Some Kendo controls fail to work correctly if they get initialized from the `bind()` component lifecycle callback. Following the [recommendation](https://github.com/aurelia/templating/issues/284#issuecomment-193941341)  we decided to initialize all Kendo controls from the `attached()` lifecycle callback.

Kendo controls are initialized and used as follows:
```
var autocomplete = jQuery("<div></div>").kendoAutoComplete().data("kendoAutoComplete");
autocomplete.doSomething();
```

The responsibility of our custom elements / custom attributes is to initialize the Kendo control and expose the `autocomplete` variable so users can interact with this object. 

A requirement of our users is to interact with the Kendo control from the screen's attached() callback. However, the screen's attached() callback is executed **before** the attached() callback of the wrapper (which initializes the Kendo control). This means that the user is unable to interact with the Kendo control from bind() or attached() because at that time the Kendo control has not yet been initialized.

What we've done so far is let users delay the attached() callback of the screen via the TaskQueue. This is not a nice solution. We can raise a DOM event when the control has been initialized on which the screen can act, but this also feels unnatural as users assume that custom elements / custom attributes completely ready as soon as the screen's attached() callback gets executed. 

This is what happens: https://gist.run/?id=8384e545986599956178955fd679299d.

**Comment by adriatic** [comment]
To prevent any miscommunication:  run the above gist and check the Chrome debugger's console to see:
```
INFO [aurelia] Aurelia Started
aurelia.js:14488 DEBUG [templating] importing resources for app.html Array[1]
aurelia.js:14488 DEBUG [templating] importing resources for ak-button.html Array[0]
app.js:3attached: undefined
app.js:4delayed attached: Objecttitle: "abcd"__proto__: Object
```

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-after-attached-plugin
