### ISSUE TITLE
We need to be able to support jQuery 3.x in the bridge

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#565]

**Comment by JeroenVinke** [comment]
Not sure what we need to do here, doesn't this work with the beta bridge?

**Comment by adriatic** [comment]
I will verify and report back here

**Comment by JeroenVinke** [comment]
The "Grid - basic use" sample works fine with jQuery 3, and our bridge does not care a lot about what version of jQuery is used (Telerik needs to make sure that all their controls work with jQuery 3).

**Comment by adriatic** [comment]
Not sure I understand this. Our decision was to tell users that Telerik requires the use of jQuery that is distributed with the SDK - or if there is some reason that the user needs something different, it should use his own under a different name than `$` (to not interfere with SDK code)

**Comment by JeroenVinke** [comment]
The safest choice is to use the jQuery version that is distributed with the SDK, but if you really want to use jQuery 3 (or any other jquery version) you can do that. But there may be some quirks when you use Kendo with jQuery 3 since it's a rather new version and [they said](http://www.telerik.com/forums/jquery-3-0#20VvfYEDvkmy4_deNHPXhg) that it is not supported. But it's up to them to support jQuery 3, not us like the title of this issue is implying ;)

**Comment by adriatic** [comment]
OK, we stated the same fact in two slightly different ways, which do not contradict with each other.

**Comment by JeroenVinke** [comment]
👍
