### ISSUE TITLE
Accessing underlying kendo UI jquery object

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#571]
I'm trying to do the following: 
```js
 activate(params, routeConfig) { 
        $("div").kendoPanelBar();
    }
```

I also tried the same thing but with the `attach()` method.

Both are resulting in an error: `kendoPanelBar is not a function`

I realize I should be using the aurelia-kendoui wrapper for this, but, I would think I could still access the underlying Kendo method?

FYI, I'm registering the controls in main.js as follows:

```js
aurelia.use.plugin('aurelia-kendoui-bridge', (kendo) => {
    kendo.kendoAutoComplete();
    kendo.kendoDateTimePicker();
    kendo.kendoDatePicker();
    kendo.kendoTemplateSupport();   
    kendo.kendoGrid();
    kendo.kendoUpload();
    kendo.kendoMultiSelect();
    kendo.useValueConverters();  

    /* For Reports */
    kendo.kendoPanelBar(); 
    kendo.kendoTreeView(); 
    kendo.kendoListView();  
  });
```

Thanks,
Jason

**Comment by smax48** [comment]
If you are using the latest 1.0.0-beta of the bridge, things are slightly more complicated.
I had the same issue when I switched to using global kendo.all.min.js (loaded in index.html via <script> tag). In this case you need to load jquery into the global scope first.
The problem is that if you ALSO have jquery as a MODULE in jspm and import it in your code like this: `import * as $ from "jquery"`, then you actually have another instance of jquery object, not the same that you used to load kendo ui. That's why you can get 'kendoSomething is not a function'.
Not sure that this situation is applicable in your case.  
Anyway, make sure that the jquery object you are using is the same that was used to initialise native Kendo UI widgets.

**Comment by jasonhjohnson** [comment]
Ah ok what's the solution?

**Comment by JeroenVinke** [comment]
I would recommend to use kendo.jQuery() which is the jQuery instance all kendo controls are loaded on. The real issue is that jQuery is loaded twice, once via script tag and once via your module loade. For example, bootstrap has a dependency on jquery, so jspm will load jquery as well

**Comment by jasonhjohnson** [comment]
Ok guys, this put me on the right track. Thank you! Digging just a bit deeper, if I use kendo.jQuery() my problem is solved, however, is there a more global way to handle this so that I don't have two versions of jQuery being used?

**Comment by smax48** [comment]
I ended up using only one global version of jquery. I need it to be global
anyway for other reasons , as well as bootstrap (I removed them both from
jspm and systemjs config). I am using typescript, so I also added jquery to
global typings.

**Comment by jasonhjohnson** [comment]
Can I see your relevant config and package files?

**Comment by adriatic** [comment]
@jasonhjohnson 
> is there a more global way to handle this so that I don't have two versions of jQuery being used?

Unless you have some special requirements for jQuery, simply use Kendo's version throughout your application. The simplest way to do that is use the script tag in your index.html, which is referencing the jQuery package from KendoUI distribution (or Telerik's CDN).

To ensure that no other jQuery instance (which could be loaded as a dependency of some other package your app is using - bootstrap is a good example) simply use the `kendo.jQuery` throughout your app to reference this "good" jQuery.

**Comment by JeroenVinke** [comment]
Keep an eye on https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/571
