### ISSUE TITLE
problems with samples caught when editing gists

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#610]
### Autocomplete: value binding:
```
Error in parsing value for 'display'.  Declaration dropped. kendo.mobile.all.min.css:24:461963
Error in parsing value for 'display'.  Declaration dropped. kendo.mobile.all.min.css:24:461996
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create index.html:8:26828
unreachable code after return statement
```

### Area charts
binding-to-remote-data and logarithmic-axis seem to be "confused about who is who". The same situation is also in the current catalog app, so please compare with http://demos.telerik.com/kendo-ui/area-charts/remote-data-binding (I got to tired to resolve this)

### Bullet charts: basic use
Does not render in FireFox 
![image](https://cloud.githubusercontent.com/assets/20169991/17534415/1ecbbc20-5e57-11e6-9421-a74637092f0c.png)

(renders fine in Chrome)

### Sparkline: aurelia
Does not render in FireFox 
![image](https://cloud.githubusercontent.com/assets/20169991/17535342/f45791e4-5e5b-11e6-9e4c-21ea88241554.png)

(renders fine in Chrome)

___Note: I tried to look at Firefox console - and for just running this sample I get a ton of output that does not make sense. These few samples would have to be examined separately as it seems that Firefox has some problems with `kendo.all.min.js`___

### Charts treemap: basic use
Does not render in FireFox

**Comment by JeroenVinke** [comment]
panel bar - events shows ak-window

**Comment by JeroenVinke** [comment]
Fixed these issues except

> Error in parsing value for 'display'.  Declaration dropped. kendo.mobile.all.min.css:24:461963
Error in parsing value for 'display'.  Declaration dropped. kendo.mobile.all.min.css:24:461996
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create index.html:8:26828
unreachable code after return statement

I'm not getting "Error in parsing value for 'display'.  Declaration dropped. kendo.mobile.all.min.css:" in firefox.

"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create index.html" is caused by gist.run, so we're getting that in every gist

"unreachable code after return statement" is a warning that bluebird throws because of a promise in aurelia-framework that's not returned. aurelia-skeleton-navigation's now hides bluebird warnings

**Comment by gist-master** [comment]
+ack
