### ISSUE TITLE
Grid not bind to data in custom element

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#622]
@JeroenVinke  hey friend.
I'm trying to create a custom element for the grid.
 the data fetched from the parent view model and passed to the grid, and from some wired reason the data not displayed on the grid.
i have created this [gist](https://gist.run/?id=93b31fb2cb6df849a478a8559dc180ac) to show my problem.
can u please help me with that :) ?

**Comment by JeroenVinke** [comment]
Hey @eliavmaman 

If you use @inject on the <grid> custom element then the instance of the view-model is not the same instance of what's actually used. Because `Grid` is a custom element it is not a singleton, and @inject will give you a new instance. So if you set a property in that instance you willl not see any change, because this view-model is not actually used.

Also, you had `k-auto-bind.bind="false"` which tells the grid not to load data on initialization, which is what you want: https://gist.run/?id=22125fb22b44786d2b4ebb5e58f85453

**Comment by eliavmaman** [comment]
@JeroenVinke 10x man it works , and thank you for explaining the meaning of ```view-model.ref```.
