### ISSUE TITLE
ak-menu & ak-datetimepicker issues

### ISSUE THREAD

**Issue by mbenedyk** [aurelia-ui-toolkits/aurelia-kendoui-bridge#646]
Hi,
I have problem with menu and datetimepicker behavir:

**`ak-menu`**
When Im setting options in HTML `ak-menu="k-open-on-click: true; k-close-on-click: false;"` first param `k-open-on-click` works as expected, but in case of `k-close-on-click` theres no effect at all.

I end up with really strange behavior when i combined `menu` with `datetimepicker`.

I prepared [gist ](https://gist.run/?id=37981aae213f6dabb96bced2de798657)to ilustrate issues.
`1)` menu is closed when i select date in first menu element.
When i try to do same with second menu element im unable to select date because menu is closing(applies also for `2)`).

Same solution with pure kendo works:
Please paste in kendo dojo to see same example:
[kendo_dojo_example.txt](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/files/538433/kendo_dojo_example.txt)

I apoligize in advance for my mistakes - if there are any.
Also if more claryfication is needed let me know.

**Comment by JeroenVinke** [comment]
Hi @mbenedyk 

Since you are binding to booleans (`k-close-on-click: false`) you should use `.bind`: `k-close-on-click.bind: false`). This changes the behavior: https://gist.run/?id=d1cc15c883dc54dbfbe768c41903a285

More on this can be found [here](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/what_you_need_to_know.html#594-when-to-bind-and-not-to-bind)

> I apoligize in advance for my mistakes

No need!

**Comment by mbenedyk** [comment]
Thanks for help
