### ISSUE TITLE
Page/route won't come up when using control on it (bridge beta)

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#647]
Hi,

I'm using the CLI and followed the installation instructions accordingly but can't get a route to load when it has a bridge control on it (in this case a button). I see this in the debugger when I click to go to my list page, so it sounds like the `require` portion is working:
`DEBUG [templating] importing resources for /list.html ["aurelia-kendoui-bridge/button/button"]`

If I leave the `require` statement in but remove the `<button ak-button>` element then the list route comes up.

Here's my relevant code:

`list.html`

``` html
<template>  
  <require from="aurelia-kendoui-bridge/button/button"></require>
  <h1>Button Test</h1>

  <button ak-button>Primary Button</button>   
</template>
```

`main.js`

``` javascript
  // ....
  aurelia.use.plugin('aurelia-kendoui-bridge');
 // ....
```

`aurelia.json`

``` json

 "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"      
          ],
          "stub": false
        }
      ]
    // ...
"bundles": [    
      {
        "name": "vendor-bundle.js",     
        "dependencies": [
         "jquery",        
          {
              "name": "kendo",
              "path": "../node_modules/kendo/"
          },
          {
                "name": "aurelia-kendoui-bridge",
                "path": "../node_modules/aurelia-kendoui-bridge/dist/amd",
                "main": "index"
          }      
```

If I put `import 'kendo/js/kendo.button';` in `app.js` then it seems to work. Am I supposed to import all of the controls I want to use that way?

I'm not sure what else to try.

Thanks,
Jason

**Comment by JeroenVinke** [comment]
> If I put import 'kendo/js/kendo.button'; in app.js then it seems to work. Am I supposed to import all of the controls I want to use that way?

Well you have two options. You can use import statements (so you're using a module loader) or you can load kendo via a script tag in index.html (kendo.all.min.js for example). 

I would recommend using import statements as you already have the module loader configured. I believe you can put the `import 'kendo/js/kendo.button'` statement in `list.js` instead of `app.js`

**Comment by jasonhjohnson** [comment]
@JeroenVinke Ah okay well that clears things up knowing I have to import each control I want to use. Sorry I guess I missed that concept in the installation instructions.

**Comment by adriatic** [comment]
@jasonhjohnson assuming that you may like to understand a bit more than just "your app needs to specify which KendoUI will use", please check this article https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-architecture/content/new_architecture.html

In order to use this feature, you need the bridge version 1.0.0-beta.1.x.x

**Comment by JeroenVinke** [comment]
I believe that this issue has been resolved
