### ISSUE TITLE
dynamic Grid model is not change after model has changed

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#666]
@JeroenVinke hey
I have cretaed that [Gist](https://gist.run/?id=82d16d440e12b08788bcb54ab11e8c8c) that display my problem.

I need to create a dynamic Kendo grid Base on schema from server, the schema is changing all the time so i uses a dynamic grid rendering.
the problem is that after the first loading (which works great) the grid doesn't load the data anymore..
any suggestions mate?

**Comment by JeroenVinke** [comment]
@eliavmaman Kendo does not re-render the grid when you change the datasource (or the model in the datasource). You may be experiencing difficulties with a dynamic grid because the wrappers of the kendo bridge were not built for that purpose. The wrappers exist so that you can initialize kendo controls declaratively from your HTML, something that does not help you with dynamic rendering. 

I would recommend not using the ak-grid wrapper, and simply destroying and recreating the grid whenever you need to. [Here](https://gist.run/?id=342f38c1792998495e7473cf5c531aab) is what you would do

**Comment by eliavmaman** [comment]
@JeroenVinke thanks for the quick answer...
I will get your advice and will use the grid without the wrapper...

thanks for been so dedicate to that project.  :)
