### ISSUE TITLE
dropdownlist filtering event, preventDefault() doesn't work

### ISSUE THREAD

**Issue by arnederuwe** [aurelia-ui-toolkits/aurelia-kendoui-bridge#691]
Hi,

I'm having an issue where using e.preventDefault() doesn't work when using the k-on-filtering.delegate wrapper on a kendo dropdownlist.
When I wire up the event the kendo way with bind(), preventDefault() behaves correctly.
I'm suspecting this is exactly the same issue as #294 

I created a gist that shows the correct and incorrect behavior: https://gist.run/?id=9f6eec20cb434541d4119b11a4b629e2

**Comment by JeroenVinke** [comment]
Thanks for creating this issue. Take a look at [this gist](https://gist.run/?id=89296105b34df696c4d5c70f0078025f). What the bridge does is raise its own event whenever Kendo raises an event (so there are two different events). When the bridge raises the event you are subscribing to, it puts the original (kendo) event in the `detail`  property of the event.

So instead of calling `.preventDefault()`  on the $event, you need to call `.preventDefault`  on `$event.detail`.

I have an idea on how to improve this, by letting the bridge propogate the `.preventDefault()` action to the event raised by Kendo

**Comment by arnederuwe** [comment]
Thanks for clarifying this, calling the one in detail indeed works perfectly!

**Comment by JeroenVinke** [comment]
Well, I added a feature that propogates `.preventDefault()` back to Kendo, but this caused an issue (https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/733). Aurelia calls `.preventDefault()` by default when the return value of the handler is not `true`, and the bridge propogates `.preventDefault()` to Kendo which can lead to unintentional behavior. So if you'd like to use this feature in the version i'm about to release, 1.4.0, you need to do the following in main.js:

```
.plugin('aurelia-kendoui-bridge', config => config.propogatePreventDefault())
```
