### ISSUE TITLE
Grid icons not showing correctly

### ISSUE THREAD

**Issue by arvadevy** [aurelia-ui-toolkits/aurelia-kendoui-bridge#694]
Some icons in the grid are not displayed correctly. Someone an idea?

![image](https://cloud.githubusercontent.com/assets/24693253/22291105/e6e224e2-e304-11e6-87f5-132d3f3da03f.png)

These css files are included in my project:
```
    <require from="bootstrap/css/bootstrap.css"></require>
    <require from="../assets/styles/style.css"></require>
    <require from="kendo/css/web/kendo.common.min.css"></require>
    <require from="kendo/css/web/kendo.rtl.min.css"></require>
    <require from="kendo/css/mobile/kendo.mobile.all.min.css"></require>
    <require from="kendo/css/web/kendo.bootstrap.min.css"></require>
```

**Comment by JeroenVinke** [comment]
Hi,

Are you sure that you need to load `kendo.rtl.min.css` and `kendo.mobile.all.min.css`? We have thus far only needed `kendo.common.min.css` and `kendo.bootstrap.min.css`

**Comment by adriatic** [comment]
@arvadevy The easiest approach to solve your issue is to check almost any Grid sample starting with **[Basic use](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid-basic-use)** that shows the Grid navigation bar:

![image](https://cloud.githubusercontent.com/assets/2712405/22308781/59674d7e-e316-11e6-8634-071d3da0adc6.png)

And check what all .css files are needed.

**Comment by arvadevy** [comment]
I fixed it by setting:
```
.k-grid-pager {
    font-size: 12pt;
}
```
Maybe provide some way to change the font or font sizes in the grids?

**Comment by JeroenVinke** [comment]
@arvadevy glad you solved it, although I cannot reproduce it. [this gist](https://gist.run/?id=023c72bbef47863e9d3b1c8ed9638279) uses the same CSS stylesheets and seems to render fine. If you would like us to take a closer look, please reproduce it in an app that we can debug. Thanks
