### ISSUE TITLE
dialog visible configuration set to false not applying

### ISSUE THREAD

**Issue by uoc1691** [aurelia-ui-toolkits/aurelia-kendoui-bridge#706]
Trying to set k-visible: false so that the dialog does not appear automatically. It's not working. Tested it here https://gist.run/?id=58d4f7efe5f553d9ce210c8c11ad5c86 as well. No luck.

**Comment by JeroenVinke** [comment]
Hi @uoc1691,

Because `visible` is a boolean, you need to use `.bind`. More examples can be found in [this chapter](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html#594-when-to-bind-and-not-to-bind). I recommend reading other chapters in this article as well.

[Here](https://gist.run/?id=1315177de7a398b497e6395cd788253d) you can see it working.

Good luck!

**Comment by uoc1691** [comment]
Resolved. Thanks @JeroenVinke
