### ISSUE TITLE
Dragged node (in tree view) does not show any content

### ISSUE THREAD

**Issue by Reverbe** [aurelia-ui-toolkits/aurelia-kendoui-bridge#719]
Hey there, I've discovered an issue with `<ak-tree-view>` and the `dragAndDrop` feature. If I set dragAndDrop to true and also pass a template, the element that's being dragged is empty. Take a look at https://gist.run/?id=17883552381ce03122bb25a5fd528697 example (this one uses the <ak-template> component) and also https://gist.run/?id=2de14a2a35b8f182a1fcaf98496cb236 . The last example doesn't go through the `<ak-template>` component, but passes a template function (along with the `dataTextField` property). The result is the same though, the element being dragged is empty.
This works when I'm not doing it through the au-kendo bridge - https://gist.run/?id=f46747013a224eab587e8d7e1cef94a0

**Comment by JeroenVinke** [comment]
Alright, Kendo apparently uses $(elem).data('$$kendoScope') to store some additional data that is then passed to us when templates need to be compiled as the `scopeFrom` property which is currently `undefined` because we're not setting `$$kendoScope` on elements we compile:

![image](https://cloud.githubusercontent.com/assets/2189477/23822145/719ec4f0-0646-11e7-9811-53a5d624c401.png)

We need to add support for that. If you'd like to help out and submit a PR, let me give some pointers:

Install the catalog app using [these instructions](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/CONTRIBUTING.md). Then in our [template-compiler](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/template-compiler.js#L101-L125) we need to do [this](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L1011). Then in [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/template-compiler.js#L106-L118) we need to check whether `scopeFrom` is supplied (which should be the case for the treeview now), and if so use that as the dataitem like kendo-angular does [here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L999-L1001)

I will try and get to it this week, but if you'd like to give it a shot that would be great

**Comment by JeroenVinke** [comment]
@Reverbe this should be fixed in 1.2.2

**Comment by Reverbe** [comment]
cool, thanks! Will look into it :)
