### ISSUE TITLE
Dropdown event sample doesn't open dropdown

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-kendoui-bridge#733]
When looking at [this sample](https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/dropdownlist-events) I noticed the dropdown doesn't open. The [referenced gist](https://gist.run/?id=e6175d8db7adcbd7f7385a92434df6eb) works without any problems, though.

This may have been introduced with 1.2.2 as 1.2.0 and 1.2.1 still open the dropdown.

Also please notice the dropdown arrow is pointing up in the bridge while pointing down in the gist. 😏

**Comment by adriatic** [comment]
Great catch - when @Thanood first mentioned this, I thought it was an issue with a bad version of some css file

**Comment by JeroenVinke** [comment]
As mentioned in https://github.com/aurelia/binding/issues/16, aurelia prevents the default action of events when the handler does not return true. We recently added a feature that propogates `.preventDefault()` back to Kendo, but because Aurelia calls `.preventDefault()` by default, it unintentionally can stop Kendo from doing its thing

**Comment by JeroenVinke** [comment]
Fixed in 1.4.0
