### ISSUE TITLE
Grid row template based on condition

### ISSUE THREAD

**Issue by AubieDawg92** [aurelia-ui-toolkits/aurelia-kendoui-bridge#743]
I would like to be able to apply a different row template based on a value in the data (e.g. a field called "row_type").  So if row_type were "x" I would want the "x_rowTemplate" and if "y" I would want the "y_rowTemplate".  In our current knockout implementation we can use an if binding to select the appropriate template.  This link discusses a similar solution from a kendo markup perspective: http://www.telerik.com/forums/how-to-conditionally-apply-row-template

I tried a couple of variations of this, but nothing I hit on seemed to work.  Any suggestions?

**Comment by JeroenVinke** [comment]
The limiting factor here is the browser considering `<tr>` tags outside of `<table>` tags as incorrect HTML and removing the <tr> tag. I have tried using Aurelia's [`as-element` ](http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-basics/5) but that doesn't seem to work with interpolation expressions (which is what you need in order have different row templates per row type). For what it's worth, here is the gist.run I tried it in: https://gist.run/?id=e9bbe1ac8219519d26940bd22e2f5a26. 

Instead of using row templates, are column templates an option? https://gist.run/?id=fc2052f9b8601ed2b3b9a77a43ac85b5

**Comment by AubieDawg92** [comment]
I did something like this and it **seems** to be working:
`
<ak-template for="rowTemplate">`
`<compose view="./grid-definitions/${is_x ? 'x' : 'y'}_rowTemplate.html" containerless></compose>`
`</ak-template>`
