### ISSUE TITLE
grid command column not rendered when widths are specified

### ISSUE THREAD

**Issue by AubieDawg92** [aurelia-ui-toolkits/aurelia-kendoui-bridge#748]
See: https://gist.run/?id=22df44e7a08310bf9ed9647c30a39442

When the width binding is present, the widths are honored, but the command column does not render.  Remove the width binding and the command column will render; however, the column widths are auto sized to squeeze into the viewable area of the grid.

**Comment by JeroenVinke** [comment]
Hey @AubieDawg92, thanks for creating the gist!

Since the width is an integer and not a string, you need to use `k-width.bind="300"` instead of `k-width="300"`.

This is what the grid is initialized with when using `k-width="300"`:
![image](https://cloud.githubusercontent.com/assets/2189477/26497053/4a7e5622-422a-11e7-8d86-52927e788ada.png)

and this is with ` k-width.bind="300"`:

![image](https://cloud.githubusercontent.com/assets/2189477/26497087/6d69a6fa-422a-11e7-93fb-7fca1bcea1b9.png)

Here is the working gist: https://gist.run/?id=c582d0dd11eb3bb33734f29190d7818d

If you'd like to know when to use .bind and when not to, please refer to [this chapter](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html#594-when-to-bind-and-not-to-bind) of our documentation.

**Comment by AubieDawg92** [comment]
Awesome!  Thanks for the help.
