### ISSUE TITLE
Calling grid.setOptions() removes buttons from custom template column

### ISSUE THREAD

**Issue by SaucyJack** [aurelia-ui-toolkits/aurelia-kendoui-bridge#754]
I am having an issue when trying to load persisted "grid options" from local browser storage using the example provided here: 

http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid-persisting-state

I have reproduced the issue in the following gist:

https://gist.run/?id=a275d4b57ae6c3d110e6062a3146793a

1. Change any of the grid options using the tools at the bottom, e.g., page or items/page. 
2. Click the "Save Options" button at the top.
3. Change the options again to something different than selected in step 1.
4. Click "Load Options." 
5. The grid will go back to the state it was in when "Save Options" was clicked, _except_ the "Edit" buttons in the far-right column are gone.

Is this a problem with the Kendo grid, or something that is getting lost in translation in the bridge?

Thanks so much for all of your hard work! I will be checking gitter as well.

**Comment by SaucyJack** [comment]
I just noticed that it also clears the bold from the first column. Is the `ak-template` element somehow getting lost?

**Comment by JeroenVinke** [comment]
The cause is mentioned in http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#methods-setOptions as the third bulletpoint. Basically, when you do 

```
<ak-col k-title="myTitle">
  <ak-template>
    <button></button>
  </ak-template>
</ak-col>
```

we initialize the grid with:

```
{
  "columns": [{
    title: "myTitle",
    template: () => "<button></button>"
  }]
}
```

The important part is the function for the template. So if you serialize this config, the function callback is gone, and therefore the template is gone. 

The function callback is necessary because it disables Kendo's internal templating system, which would crash on some of the syntax that's used in Aurelia templates.

You may be able to get away with

```
<ak-template kendo-template.bind="true">
    <button ak-button click.delegate="edit(id)">Edit</button>
</ak-template>
```

which tells the bridge not to wrap the template into a function callback. But you are likely going to hit issues using this approach

**Comment by SaucyJack** [comment]
Thanks, @JeroenVinke . So it sounds like my best path might be to save the grid state and pass it on the query string, then use grid methods to set items-per-page and page-on options instead of using the `setOptions` method?

**Comment by JeroenVinke** [comment]
I think so, yes. Perhaps you can set those values in the datasource like it is done in https://stackoverflow.com/a/36133513/3922366

**Comment by SaucyJack** [comment]
Thanks very much, @JeroenVinke. I can't tell you how much we appreciate your work on this lib.

**Comment by GB16** [comment]
@SaucyJack can you explain how this was fixed? I am working on Kendo grid with static and dynamic columns. I tried to use getoptions and setoptions to preserve the state but it didn't work completely.
