### ISSUE TITLE
Using pro version fails on KendoConfigBuilder.prototype.pro with kendoDropdownTree missing

### ISSUE THREAD

**Issue by zinvob** [aurelia-ui-toolkits/aurelia-kendoui-bridge#799]
kendoDropDownTree is defined as kendoDropdownTree (the D should be uppercase). Once this is changed to kendoDropDownTree, see:

KendoConfigBuilder.prototype.pro = function pro() {
    this.core().kendoBarcode().kendoChart().kendoChat().kendoDiagram().kendoDropDownTree().kendoEditor().kendoFilterMenu().kendoGantt().kendoGrid().kendoMap().kendoLinearGauge().kendoPager().kendoPivotGrid().kendoQRCode().kendoRadialGauge().kendoScheduler().kendoTreeList().kendoTreeView().kendoUpload();

    return this;
  };

it works properly. Hope you can fix it soon, since I cannot use npm for this package now.

**Comment by zinvob** [comment]
Inside config-builder.js

**Comment by JeroenVinke** [comment]
Hey,

I would not recommend using this pro() function since it loads every
control when the page is loading, which is very slow.

Check our docs, there is some documentation on how to load the controls. I
recommend using require tag in the views where you use a kendo control.

I will look at the error you mentioned

Thank,

Jeroen

Op vr 13 dec. 2019 14:45 schreef Atle Smelvær <notifications@github.com>:

**Comment by zinvob** [comment]
I've created a pull request for you
#800

**Comment by zinvob** [comment]
I'll check out not loading everything :)

**Comment by JeroenVinke** [comment]
I've fixed this in 1.9.0, thanks for reporting it :)
